
verbosity: 4 # 4 debug 3 info 2 warning 1 error 0 is nothing
print_markdown: true
log_file_name: "result.md"
random_seed: 1
cpu_corecount: -1
save_best: true
save_all: true # Overrides save best so above statement doesn't matter
type: ensemble # options are [ensemble, single] default is ensemble

train_size: 0.7
test_size: 0.15
validation_size: 0.15

y_column: "status"

# sample_count: 15000
output_folder_postfix: "jiraset_ml_preprocess_ensemble_balanced"
training_path: LSST_Data_Management_stories_balanced.csv # absolute or relative to where the pipeline script is executed from
standardize_text: true
lda_topic_generation: true
skip_dim_reduction: true

ml_pre_processing:
  sentiment_analysis: true # true by default
  zeroshot_analysis:
      -
        name: urgency
        labels: ["urgent", "moderate", "not urgent"]
      -
        name: general_topic
        labels: ["art", "culture", "geography", "health and fitness", "science", "people", "technology", "engineering"]
      -
        name: se_topic
        labels: ["design", "automation", "analytics", "communication", "telemetry", "file sharing", "logistics", "performance", "security", "devops"]
      -
        name: type_topic
        labels: [feature, defect, architecture]
      -
        name: clarity
        labels: ["clear", "vague", "confusing"]
      -
        name: buzzwords
        labels: ["buzzword", "normal"]
      -
        name: complexity
        labels: ["simple", "complex"]
      -
        name: emotion
        labels: ["happy", "sad", "angry", "frustrated", "silly", "excited"]
      -
        name: testability
        labels: ["testable", "untestable"]
      -
        name: dependency
        labels: ["independent", "dependent"]
      -
        name: other_sentiment
        labels: ["good", "bad"]

# used internally
variables:
  base_fields: [points, sprint_count]

feature_variations:
  no_linked:
    x_cols_vars: [ ]
    extraction_fields: [ summary ]

  summary:
    x_cols_vars: [base_fields]
    extraction_fields: [summary]

  description:
    x_cols_vars: [base_fields]
    extraction_fields: [description]

  summary_and_desc:
    x_cols_vars: [ base_fields ]
    extraction_fields: [ summary, description ]
